<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
    <!-- We use the System.Text.Json serializer for Cosmos, so Newtonsoft.Json isn't needed. -->
    <AzureCosmosDisableNewtonsoftJsonCheck>true</AzureCosmosDisableNewtonsoftJsonCheck>
    <UserSecretsId>0b133680-fe7c-412b-93d5-152c443f0fb4</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Blazor-ApexCharts" Version="6.1.0" />
    <PackageReference Include="Microsoft.Azure.Cosmos" Version="3.62.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

</Project>
